"""Ambient correlation and request identifiers.

``CLAUDE.md`` requires a correlation id to be generated for every request and
propagated through the API, runtime, agents, tools, providers, logs and traces.

Threading an id through every function signature would couple unrelated layers
to a transport concern, so it is carried in :mod:`contextvars` instead.
``ContextVar`` values follow the ``await`` chain and are copied into tasks
created with :func:`asyncio.create_task`, which means the id survives the async
boundaries the platform is built on without any explicit plumbing.

Consumers should not read these variables directly for logging: the structlog
processor installed by ``agent_platform.telemetry.logging`` injects them into
every record automatically.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from contextvars import ContextVar, Token

__all__ = [
    "CORRELATION_ID_HEADER",
    "REQUEST_ID_HEADER",
    "bind_correlation_id",
    "bind_request_id",
    "correlation_scope",
    "get_correlation_id",
    "get_request_id",
    "reset_correlation_id",
    "reset_request_id",
]

#: Inbound header used to continue an existing trace from an upstream caller.
CORRELATION_ID_HEADER = "X-Correlation-ID"

#: Header identifying a single HTTP request. Always generated by this service.
REQUEST_ID_HEADER = "X-Request-ID"

_correlation_id: ContextVar[str | None] = ContextVar("correlation_id", default=None)
_request_id: ContextVar[str | None] = ContextVar("request_id", default=None)


def get_correlation_id() -> str | None:
    """Return the correlation id for the current context, if one is bound."""
    return _correlation_id.get()


def get_request_id() -> str | None:
    """Return the request id for the current context, if one is bound."""
    return _request_id.get()


def bind_correlation_id(correlation_id: str) -> Token[str | None]:
    """Bind ``correlation_id`` to the current context.

    Returns the token needed to restore the previous value. Prefer
    :func:`correlation_scope`, which handles restoration for you.
    """
    return _correlation_id.set(correlation_id)


def bind_request_id(request_id: str) -> Token[str | None]:
    """Bind ``request_id`` to the current context.

    Returns the token needed to restore the previous value.
    """
    return _request_id.set(request_id)


def reset_correlation_id(token: Token[str | None]) -> None:
    """Restore the correlation id that was bound before ``token`` was issued."""
    _correlation_id.reset(token)


def reset_request_id(token: Token[str | None]) -> None:
    """Restore the request id that was bound before ``token`` was issued."""
    _request_id.reset(token)


@contextmanager
def correlation_scope(
    *,
    correlation_id: str | None = None,
    request_id: str | None = None,
) -> Iterator[None]:
    """Bind identifiers for the duration of a block and restore them afterwards.

    Restoration matters in long-lived workers: without it a value set while
    handling one unit of work leaks into the next and corrupts its telemetry.
    Passing ``None`` for either argument leaves that identifier untouched.

    Example:
        >>> with correlation_scope(correlation_id="abc"):
        ...     assert get_correlation_id() == "abc"
        >>> get_correlation_id() is None
        True
    """
    correlation_token = _correlation_id.set(correlation_id) if correlation_id else None
    request_token = _request_id.set(request_id) if request_id else None
    try:
        yield
    finally:
        if request_token is not None:
            _request_id.reset(request_token)
        if correlation_token is not None:
            _correlation_id.reset(correlation_token)
